### ISSUE TITLE
Be consistent with visual attributes

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/SOmap#21]
Note for future reference: need to give each layer its full set of attributes so that the user has access to them later if they want to tailor them. e.g. the MPA layer implicitly has no fill colour, and it's not an attribute of the `$mpa` component of the `SOmap` object, so the user can't control it.

**Comment by Maschette** [comment]
We could add them as we see them and set them as NULL/NA?

**Comment by raymondben** [comment]
Am thinking we could potentially add `...` to the actual plot calls, and then just transparently pass any extra parms that the user (or us, at a later date) might add to the data layer object, without having to explicitly code them. Not urgent, though, can worry about it later.

**Comment by raymondben** [comment]
As of https://github.com/AustralianAntarcticDivision/SOmap/commit/7baaecc281cbec48375129a99b4a37829b4dcbce the following happens with `SOmap` and `SOmanagement`:

**Comment by Maschette** [comment]
I think this is mostly in place for the SOauto_map stuff it probably needs the plot stuff tidied up. 
I am thinking on a better was to do SOleg; it works ok now but I think it could be better. @mdsumner mentioned he had a better way to do the plot rather than a graticule. I wonder about making it a stand alone SOmap object or if you could append it to an existing object or whether we bother and just leave it as is currently?

**Comment by raymondben** [comment]
Time has passed, this is no longer particularly relevant (mostly been implemented).
