### ISSUE TITLE
Weird example

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#22]
Why does the readme example go to such a high latitude ( https://github.com/AustralianAntarcticDivision/SOmap/blob/master/man/figures/README-automap-spatial-1.png ) 
Surely the extent of the fronts layer does not go up that high?

**Comment by mdsumner** [comment]
It's actually a pretty complicated series of steps to figure out the overall extent, the logic doesn't only take into the account the fronts or vectors, it also tries to find a centre given what was supplied (it's not the pole). I guess this is where the auto-dream conflicts with your polar fixation.   How about just changing the example? 

``` r
library(SOmap)
#> Loading required package: raster
#> Loading required package: sp
mydata <- SOmap_data$fronts_orsi
SOauto_map(mydata, family = "laea", centre_lon = 147, centre_lat = -90, input_points = FALSE, lcol = 2)
```

![](https://i.imgur.com/PlG3FNz.png)

<sup>Created on 2019-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

It doesn't look different to a polar stereographic, because in this kind of region they are very similar, so the point I was angling for is not made (but I can do it so all is well). ;)

**Comment by mdsumner** [comment]
I guess it might make sense to set `centre_lat = -90` as a default, given the basic "turn the wheel" motivation here - and allow the ability to *unset* it, i.e. `centre_lat = NULL` for use by weird people - so it does the auto-centre thing?   It's a good example, and probably makes a good line in the sand for what this package is (by default)!

**Comment by Maschette** [comment]
I think it is fine in the projection but it is blowing it out to the max extent of the bathymetry rather than the max of the data? compared to:
` SOauto_map(mydata, family = "laea", centre_lon = 147,  input_points = FALSE, lcol = 2,mask = T)`

![rplot](https://user-images.githubusercontent.com/14663215/53486905-2803d000-3ade-11e9-9bda-d10791f07f77.png)

**Comment by mdsumner** [comment]
Oh I see, I think
