### ISSUE TITLE
Add more reprojection options for SOproj

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#23]
Currently works for lat long points but should be expanded for other objects, eg raster, polygons, lines etc...

**Comment by raymondben** [comment]
A few suggestions here:
- use `map$projection` not `map$crs` because `$projection` is consistent between `SOmap` and `SOauto_map` objects. I'd like to remove the `crs` component (which is only in `SOauto_map` objects) but I haven't yet checked if it's relied on by other code
- but really we should create functions for accessing the components of `SOmap`/`SOauto_map` objects, rather than having the user access the actual components directly (e.g. the user should be doing `projection(map)` not `map$projection`, where `projection(...)` is our function). This will mean that we can modify the actual object structure at a later time if necessary, and just update the relevant function, without breaking any downstream user code
- suggest that the `crs` parameter to `SOproj`/`SOplot` should be renamed to `target`, and it should accept any of a projection string, CRS object, or an `SOmap` or `SOauto_map` object (from which it should extract the projection)

**Comment by mdsumner** [comment]
Well there is reproj package which requires target and source args, unless you import the generic and wrap with your own methods. I don't think users have to know this stuff at all if the original setup projection is suitable. That's what I'm angling for anyhoo ..

**Comment by Maschette** [comment]
The aim for this was more to make it easier to do the same for other object types. SOproj works great for points but not things like rasters or polygons etc. so I think it is just a matter of having method options for them.

**Comment by mdsumner** [comment]
If the function is to be SOproj(...) then it needs to be (something like) SOproj(x, target, ..., source = NULL)  - so x is a matrix  lon,lat or raster etc.  I think that's ok. I just pushed some more stuff using reproj, so there's an internal (not exported for users) method on reproj for raster, sp, and sf, as well as the basic reproj(xy, ...) that's used. 

1d09332


(Ben and me discussed a bunch of other improvements to the object as well)

**Comment by mdsumner** [comment]
Now works for `x` as a matrix or `x`, `y` as paired vetors, or `x` is a raster, or sp, or sf, or SOauto_map or SOmap, BUT it's super confusing for me atm  because I tend to do 

```R
SOproj(x, "+proj=lcc etc")
```

which is wrong!  If y is character it errors, you have to use

```R
SOproj(x, target=  "+proj=lcc etc")
```

or 

```R
SOproj(xvector, yvector, "+proj=lcc etc")
```

which is a bit naff. Needs more thought.

**Comment by Maschette** [comment]
one option would be something along the lines of assuming if y is a character it is meant to be target but that's a bit dangerous. 

Am I reading the code right that we have moved away from assuming source is lonlat if no source is provided?

**Comment by mdsumner** [comment]
No that's intended to be as is - I got confused lower in the function dealing with objects, but I think everything that's not vectors or matrix should shortcut in the early return, because objects (raster, sp, sf etc) should have projection crs set - I'm unsure about assuming an NA crs means lonlat, but if we wrap in raster's couldBeLonLat then I think that'd be ok. 

This function should be turned into a generic with methods, so the behaviour is clearer - but I'm still a bit unsure about this y/target thingo. I also wonder if we should just remove SOproj, and make SOplot do all the work internally. I want `reproj()` do all the work, but there you have to provide a matrix or object.

**Comment by Maschette** [comment]
I would prefer it to default to lonlat even if only for cases where !missing(x) && !missing(y) as that is the most likely case where it will be lonlat. 

With regards to the doing it all in SOplot, I don't see any reason we can't export SOproj but still have it called inside SOplot. That way if people want to reproject for ggplot2 or something they can still use SOproj?

**Comment by mdsumner** [comment]
Oh you are right SOproj(x) looks up the current plot crs, which is the point

**Comment by Maschette** [comment]
i'm pretty happy with this; are we going to add more options or shall we close this issue?

**Comment by mdsumner** [comment]
Close it! Celebrate this win before it gets more difficult!
