### ISSUE TITLE
title doesn't work well

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/SOmap#26]
``` r
library(SOmap)
#> Loading required package: raster
#> Loading required package: sp
track <- SOmap_data$mirounga_leonina
print(SOauto_map(track$lon, track$lat, family = "lcc"))
title(main = "Lambert Conformal Conic")
```

![](https://i.imgur.com/V5QW2RF.png)

<sup>Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Maschette** [comment]
This was a par issue in the print method. I added a `main` options for print. I need to link it back to `SOmap` and `SOauto_map` so that you can put it into them and it becomes part of the SOmap object and print looks for it there, but this should work now: 

```
library(SOmap)
#> Loading required package: raster
#> Loading required package: sp
track <- SOmap_data$mirounga_leonina
print(SOauto_map(track$lon, track$lat, family = "lcc"),main = "Lambert Conformal Conic")
```
![image](https://user-images.githubusercontent.com/14663215/54725754-61eb6200-4bc4-11e9-89af-1be423dad1c8.png)

**Comment by mdsumner** [comment]
Oh nice - the other thing is xpd, we are getting clipped - I think the whole aspect thing needs a revisit ...  using main like that is much better
