### ISSUE TITLE
Give SOmanagement projection options

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#31]
No that we have `SOproj()`, we should be able to give `SOmanagment() `options for projection or SOmap objects and have it reproject. 

This will be more useful for `SOauto_map()` than it will for `SOmap()` So we can add management boundaries to smaller areas. 

Probably not as easy as I like to think it is.

**Comment by Maschette** [comment]
The projection part is quite simple using SOproj, the cropping part is ugly but @mdsumner does this already for the coastline in SOauto_map so we can bastardise that code. A working example is: 

```
a<-SOauto_map(c(0, 50), c(-70, -50))

x<-SOproj(SOmap_data$CCAMLR_SSRU, target = a$projection)

coastline <- try(as(sf::st_crop(sf::st_buffer(sf::st_transform(sf::st_as_sf(x), a$projection), 0), xmin = raster::xmin(a$bathy), xmax = raster::xmax(a$bathy), ymin = raster::ymin(a$bathy), ymax = raster::ymax(a$bathy)), "Spatial"), silent = TRUE)

plot(coastline, border=2, add=TRUE)
```

![image](https://user-images.githubusercontent.com/14663215/55272637-932a0780-5313-11e9-96ea-423db1600f7a.png)

**Comment by Maschette** [comment]
So I have turned the SOproj + try combo into SOauto_crop()

I am wondering what the easiest way to apply it to all the true layers in SOmanagement. @raymondben Do you think it would be easier to reproject the objects in 'out' as the final step?

**Comment by Maschette** [comment]
Something like this but not a for loop for obvious reasons.... 

 if (!missing(x)){
   for(i in names(out)[3:length(names(out))])
   out[[i]]$plotargs$x<-SOauto_crop(layer = out[[i]]$plotargs$x, x=x)
   }

**Comment by Maschette** [comment]
Something like: 
`lapply(names(out)[3:length(out)], function(x) SOauto_crop(out[[x]]$plotargs[['x']], a))`

but working out how to do the reassignment is proving the be a pain in the ass. #lapplySucks

**Comment by mdsumner** [comment]
You need eval().

Actually I am joking, a for loop is fine here

**Comment by Maschette** [comment]
The lapply works I just cant work out to assign it back but I am sooooo out of my depth in the apply family.

**Comment by raymondben** [comment]
Few things here:
- don't rely on the ordering of things within the object - `names(out)[3:length(out)]` will break if the ordering changes. Use `setdiff(names(out), c("parts", "not to", "reproject"))` instead
- `lapply` sucks here because it's not really the right thing to be using! `lapply` returns the result of each function evaluation in a list. You could do something like `temp <- lapply(...); out <- c(out[c("parts", "not to", "reproject")], temp)` but it's not pretty. Using `<<-` in the inner function to assign to the parent-scoped object is no better (I would say worse)
- this is one instance where I think a `for` loop is better: firstly the code will end up being much more readable (maintainable), and secondly the slow part of this whole thing is the reprojection operation. Speeding things up ever so fractionally by `lapply`ing instead of looping will surely not make a noticeable difference?

**Comment by Maschette** [comment]
Cheers Ben, The for loop almost works for some reason when I use the for loop the
 `structure(out, class = "SOmap_management")`
Doesn't?
 
Ordering changes? :P I know its not the best I always forget setdiff exists and not sure how to use it in this context. 

I just pushed it if your interested.

**Comment by raymondben** [comment]
can you give me an example to run it with pls? What is the basemap arg supposed to be?

**Comment by Maschette** [comment]
a<-SOauto_map(c(0, 50), c(-70, -50))
SOmanagement(CCAMLR=TRUE, SSRU=TRUE, basemap=a)

basemap was what I went with but it should probably be something else.

**Comment by raymondben** [comment]
possibly working now, at least for your example. It won't work for `SOmanagement(IWC = TRUE)` because the IWC data is just a matrix, and the new auto-reproj doesn't know how to handle it yet

**Comment by Maschette** [comment]
The IWC thing is easier to reproject, for it and the labels I have made out$projection based on an if function where if basemap is present it becomes the projection of basemap. 
But to avoid the for loop trying to assess it I assume I will need to add IWC to the setdiff?

**Comment by raymondben** [comment]
Would it be better to make the object's IWC data into an sp/sf object, so that the existing reproj code just knows what to do with it? (WIll need the current IWC plotting code to be adjusted, presumably). I think (could be wrong) that overall this will make things generally more consistent and simplify the code?

**Comment by Maschette** [comment]
Urgh the IWC thing was easy but I just realised for all the labels it pulls out the coordinates based on the "standard" projection so we would have to reproject all the labels as well. 

But yes turning the IWC layer into a sp/sf object will probably be easier, their should be a shapefile available for it somewhere I just couldn't find it from memory last time. I will check again. With the labels thing I was hoping the SOauto_crop would work as well but alas it appears not to.

**Comment by mdsumner** [comment]
All the objects in management should be formal, pulled out into a new data object, and we ensure that `reproj()`ection and crop methods work for them. How about that as a first step, pull out the code for each layer and turn it into sp in polar stereo?

**Comment by Maschette** [comment]
They already are sp objects in polar stereo within SOmap_data

**Comment by raymondben** [comment]
Not all of them, e.g. IWC is constructed on the fly in SOmanagement
